name: Deploy Content to xuhu-ilc [cf981074-498a-487c-9b4d-5351cee4ea7c]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-cf981074-498a-487c-9b4d-5351cee4ea7c.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ samuelkuangms-patch-1 ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-cf981074-498a-487c-9b4d-5351cee4ea7c.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'enes-testresourcegroup'
      workspaceName: 'xuhu-ilc'
      workspaceId: 'b5831f8f-f947-432e-ae5b-dca753d8f7a6'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AutomationRule'
      branch: 'samuelkuangms-patch-1'
      sourceControlId: 'cf981074-498a-487c-9b4d-5351cee4ea7c'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_cf981074498a487c9b4d5351cee4ea7c }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_cf981074498a487c9b4d5351cee4ea7c }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_cf981074498a487c9b4d5351cee4ea7c }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_cf981074498a487c9b4d5351cee4ea7c }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_cf981074498a487c9b4d5351cee4ea7c }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_cf981074498a487c9b4d5351cee4ea7c }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_cf981074498a487c9b4d5351cee4ea7c }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_cf981074498a487c9b4d5351cee4ea7c }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_cf981074498a487c9b4d5351cee4ea7c }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-cf981074-498a-487c-9b4d-5351cee4ea7c.ps1