name: Deploy Content to a-luna-test-0 [aa371e21-f3b0-417d-8581-548d0691d1c5]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-aa371e21-f3b0-417d-8581-548d0691d1c5.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ samuelkuangms-patch-1 ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-aa371e21-f3b0-417d-8581-548d0691d1c5.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'a-luna-rg'
      workspaceName: 'a-luna-test-0'
      workspaceId: 'bc14d9a7-86e4-4c33-b9a8-1f39ef50a911'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureChinaCloud'
      contentTypes: 'Playbook'
      branch: 'samuelkuangms-patch-1'
      sourceControlId: 'aa371e21-f3b0-417d-8581-548d0691d1c5'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_aa371e21f3b0417d8581548d0691d1c5 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_aa371e21f3b0417d8581548d0691d1c5 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_aa371e21f3b0417d8581548d0691d1c5 }}
        environment: 'AzureChinaCloud'
        audience: api://AzureADTokenExchangeChina
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_aa371e21f3b0417d8581548d0691d1c5 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_aa371e21f3b0417d8581548d0691d1c5 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_aa371e21f3b0417d8581548d0691d1c5 }}
        environment: 'AzureChinaCloud'
        audience: api://AzureADTokenExchangeChina
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_aa371e21f3b0417d8581548d0691d1c5 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_aa371e21f3b0417d8581548d0691d1c5 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_aa371e21f3b0417d8581548d0691d1c5 }}
        environment: 'AzureChinaCloud'
        audience: api://AzureADTokenExchangeChina
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-aa371e21-f3b0-417d-8581-548d0691d1c5.ps1