name: Deploy Content to TestWkSpace [470dbab5-bd6b-45b2-99a7-4bf850230eab]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-470dbab5-bd6b-45b2-99a7-4bf850230eab.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ samuelkuangms-patch-1 ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-470dbab5-bd6b-45b2-99a7-4bf850230eab.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'newecotestrg2'
      workspaceName: 'TestWkSpace'
      workspaceId: 'd67b16c8-7718-48cc-bb81-6b1d47ccbc3f'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzurePPE'
      contentTypes: 'AnalyticsRule'
      branch: 'samuelkuangms-patch-1'
      sourceControlId: '470dbab5-bd6b-45b2-99a7-4bf850230eab'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_SENTINEL_CLIENTID_470DBAB5BD6B45B299A74BF850230EAB }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_SENTINEL_TENANTID_470DBAB5BD6B45B299A74BF850230EAB }} 
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_470DBAB5BD6B45B299A74BF850230EAB }}
      continue-on-error: false
      id: login1
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Add-AzEnvironment `
          -Name AzurePPE `
          -ActiveDirectoryEndpoint https://login.windows-ppe.net `
          -ResourceManagerEndpoint https://management.azure.com/ `
          -ActiveDirectoryServiceEndpointResourceId https://management.core.windows.net `
          -GraphEndpoint https://graph.ppe.windows.net/ | out-null;
          $oidcTokenParams = @{
           Uri            = $env:ACTIONS_ID_TOKEN_REQUEST_URL
           Body           = @{
                 audience = 'api://AzureADTokenExchange'
           }
           Authentication = 'Bearer'
           Token          = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
          }
          $IdToken = (Invoke-RestMethod @oidcTokenParams).value
          $applicationId = $env:AZURE_CLIENT_ID
          $tenantId = $env:AZURE_TENANT_ID
          $subscription = $env:AZURE_SUBSCRIPTION_ID
          Clear-AzContext -Force #This is only necessary on self-hosted runners
          $connectAzAccountParams = @{
           ServicePrincipal = $true
           ApplicationId    = $applicationId
           TenantId         = $tenantId
           Subscription     = $subscription
           FederatedToken   = $IdToken
           Environment      = 'AzurePPE'
           Scope            = 'CurrentUser' #Future steps can use this context, it will be thrown away at the end of run
           WarningAction    = 'SilentlyContinue' #Suppresses a warning about the client assertion saved in AzureRmContext.json
          }
          $context = Connect-AzAccount @connectAzAccountParams
          if (-not $context) { throw 'Connect-AzAccount ran but no context was returned. This is probably a bug.' }
          "Connected to $($context.Context.Account)"

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Add-AzEnvironment `
          -Name AzurePPE `
          -ActiveDirectoryEndpoint https://login.windows-ppe.net `
          -ResourceManagerEndpoint https://management.azure.com/ `
          -ActiveDirectoryServiceEndpointResourceId https://management.core.windows.net `
          -GraphEndpoint https://graph.ppe.windows.net/ | out-null;
          $oidcTokenParams = @{
           Uri            = $env:ACTIONS_ID_TOKEN_REQUEST_URL
           Body           = @{
                 audience = 'api://AzureADTokenExchange'
           }
           Authentication = 'Bearer'
           Token          = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
          }
          $IdToken = (Invoke-RestMethod @oidcTokenParams).value
          Connect-AzAccount -ServicePrincipal -Tenant ${{ secrets.AZURE_SENTINEL_TENANTID_470dbab5bd6b45b299a74bf850230eab }} -Subscription ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_470dbab5bd6b45b299a74bf850230eab }} -ApplicationId ${{ secrets.AZURE_SENTINEL_CLIENTID_470dbab5bd6b45b299a74bf850230eab }} -Environment AzurePPE -FederatedToken $IdToken | out-null;

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Add-AzEnvironment `
          -Name AzurePPE `
          -ActiveDirectoryEndpoint https://login.windows-ppe.net `
          -ResourceManagerEndpoint https://management.azure.com/ `
          -ActiveDirectoryServiceEndpointResourceId https://management.core.windows.net `
          -GraphEndpoint https://graph.ppe.windows.net/ | out-null;
          $oidcTokenParams = @{
           Uri            = $env:ACTIONS_ID_TOKEN_REQUEST_URL
           Body           = @{
                 audience = 'api://AzureADTokenExchange'
           }
           Authentication = 'Bearer'
           Token          = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
          }
          $IdToken = (Invoke-RestMethod @oidcTokenParams).value
          Connect-AzAccount -ServicePrincipal -Tenant ${{ secrets.AZURE_SENTINEL_TENANTID_470dbab5bd6b45b299a74bf850230eab }} -Subscription ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_470dbab5bd6b45b299a74bf850230eab }} -ApplicationId ${{ secrets.AZURE_SENTINEL_CLIENTID_470dbab5bd6b45b299a74bf850230eab }} -Environment AzurePPE -FederatedToken $IdToken | out-null;

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-470dbab5-bd6b-45b2-99a7-4bf850230eab.ps1
