name: Deploy Content to TestWkSpace [106d65d8-9f92-4c4a-87bc-3daab86aac20]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-106d65d8-9f92-4c4a-87bc-3daab86aac20.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ samuelkuangms-patch-1 ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-106d65d8-9f92-4c4a-87bc-3daab86aac20.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'newecotestrg2'
      workspaceName: 'TestWkSpace'
      workspaceId: 'd67b16c8-7718-48cc-bb81-6b1d47ccbc3f'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzurePPE'
      contentTypes: 'AnalyticsRule'
      branch: 'samuelkuangms-patch-1'
      sourceControlId: '106d65d8-9f92-4c4a-87bc-3daab86aac20'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_106d65d89f924c4a87bc3daab86aac20 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_106d65d89f924c4a87bc3daab86aac20 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_106d65d89f924c4a87bc3daab86aac20 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_106d65d89f924c4a87bc3daab86aac20 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_106d65d89f924c4a87bc3daab86aac20 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_106d65d89f924c4a87bc3daab86aac20 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_106d65d89f924c4a87bc3daab86aac20 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_106d65d89f924c4a87bc3daab86aac20 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_106d65d89f924c4a87bc3daab86aac20 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-106d65d8-9f92-4c4a-87bc-3daab86aac20.ps1